name: TEST public

on:
  workflow_dispatch:

jobs:
  build_and_push_ECR:
    runs-on: ubuntu-22.04
    env:
      name: ${GITHUB_REPOSITORY#*/}"-env"
      tag: ${GITHUB_SHA}
      ECR_REGISTRY: "public.ecr.aws/"${{ vars.REPOSITOTY_NAME }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Build docker image
        run: |
          docker build . -t ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }}
          docker tag ${{ env.ECR_REGISTRY }}/${{ env.name }}:${{ env.tag }} ${{ env.ECR_REGISTRY }}/${{ env.name }}:latest

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
            mask-password: 'true'
            registry-type: public

      - name: Push docker image to Amazon ECR Public
        run: |
            docker push ${{ env.ECR_REGISTRY }}:${{ env.tag }} 
            docker push ${{ env.ECR_REGISTRY }}:latest