variables:
  ECR_REGISTRY: $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  APP_NAME: $ECR_NAME
  DOCKER_HOST: tcp://docker:2375

publish:
  image:
    name: amazon/aws-cli
    entrypoint: [""]
  services:
    - docker:dind
  before_script:
    - amazon-linux-extras install docker
    - aws --version
    - docker --version
  script:
    - docker build -t $ECR_REGISTRY/$APP_NAME:$CI_PIPELINE_IID .
    - docker tag $ECR_REGISTRY/$APP_NAME:$CI_PIPELINE_IID $ECR_REGISTRY/$APP_NAME:latest
    - aws ecr get-login-password | docker login --username AWS --password-stdin $ECR_REGISTRY
    - docker push $ECR_REGISTRY/$APP_NAME:$CI_PIPELINE_IID
    - docker push $ECR_REGISTRY/$APP_NAME:latest
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "main")
